info:
    app:
        profile: developer
        name: "@name@"
        description: "@description@"
        version: "@project.version@"

server:
    context-path: /

heimdall:
    contextPath: /heimdall/v1
    hostname: hostname
    excludeRabbit: true
    retryable: false
    logstash:
        enabled: true
        destination: 127.0.0.1
    rewrite:
        enable: false
        prefix: heimdall
    datasource:
        initializationFailTimeout: -1
        dataBaseType: POSTGRESQL
        socketTimeout: 10000
        loginTimeout: 10000
        minimumIdle: 0
        maximumPoolSize: 50
        validationTimeout: 10000
        idleTimeout: 10000
        connectionTimeout: 10000
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        connectionTestQuery: SELECT 1
        autoCommit: false
        initializationFailFast: false
        appName: HEIMDALL
        databaseName: heimdall
        portNumber: 5432
        serverName: 127.0.0.1
        username: postgres
        password: 123456
        runLiquibase: true
        sendStringParametersAsUnicode: false
    mongo:
        enabled: false
#        serverName:
        url: mongodb://admin:admin@localhost
        port: 27017
        dataBase: logging
        collection: logs
        username: admin
        password: admin
        queueSize: 500
        discardingThreshold: 0
        zoneId: America/Sao_Paulo
    trace:
        printAllTrace: true
        sanitizes:
            - access_token
            - client_id
    redis:
        host: 127.0.0.1
        port: 6379 
        maxTotal: 128
        maxIdle: 128
        minIdle: 16
        testOnBorrow: true
        testOnReturn: true
        testWhileIdle: true
        minEvictableIdleTimeSeconds: 60
        timeBetweenEvictionRunsSeconds: 30
        numTestsPerEvictionRun: 3
        blockWhenExhausted: true
        connectionPoolSize: 10
    middlewares:
        allowInactive: 0
        deleteDeprecated: false
    failsafe:
        failureNumber: 4
        sucessNumber: 4
        delayTimeSeconds: 30

spring:
    pid:
        fail-on-write-error: false
        file: heimdall.pid
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: POSTGRESQL
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    jackson:
        serialization:
            INDENT_OUTPUT: true
            WRITE-DATES-AS-TIMESTAMPS: false
    rabbitmq:
        host: 127.0.0.1
        port: 5672
        #virtual-host: dev
        requested-heartbeat: 10
    cache:
        type: redis

endpoints:
    env:
        keys-to-sanitize: url, host, serverName
    routes:
        enabled: true
        sensitive: false
    actuator:
        enabled: true
    trace:
        filter:
            enabled: false

management:
    context-path: /manager
    security:
        enabled: false
    health:
        mongo:
            enabled: false
        redis:
            enabled: false
        rabbit:
            enabled: false
        hystrix:
            enabled: false
        refresh:
            enabled: false

zuul:
    ignoredPatterns: /manager/**
    include-debug-header: false
    debug: 
        parameter: debug
        request: false
    filter:
        root: /tmp/interceptores
        interval: 8
    host: 
        socket-timeout-millis: 40000
        connect-timeout-millis: 40000  

security:
    basic:
        enabled: false
